### ISSUE TITLE
Todo post-november contract

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-first-aid-kit#16]
[November for reference](https://github.com/ssbc/ssb-first-aid-kit/issues/3)

* [x] tell people in the readme usage instructions to run another client at the same time
* [x] make pretty screenshot, above pretty image background
* [x] make a 1.3 post. ask people to test it, come with feedback. [delete their indexes](https://github.com/ssbc/ssb-first-aid-kit/issues/15). be clear that i'm not gonna be maintaining it (contract's out), people can contribute. if people want to contribute, contact mix for dev support
* [x] maybe tweet about 1.3 as well,

**Comment by Powersource** [comment]
Updated the screenshot using https://www.screely.com/

![image](https://user-images.githubusercontent.com/1427063/71929054-1331a780-3199-11ea-95d9-ef65114104aa.png)

**Comment by Powersource** [comment]
Made a post `%ftHCQ/2PvWjys7KKH2oO7PwMMj+aAXFXn7/pryultJI=.sha256`

**Comment by Powersource** [comment]
twoot https://twitter.com/The_lolness/status/1214673685862387712
