### ISSUE TITLE
Todo november

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-first-aid-kit#3]
discussed with mix what things make sense to do for this sprint and got this

- features
  - [x] delete flume indexes
  - [x] add progress reports for each index
    - e.g. backlinks TICK (done)
    - e.g. query WORKING (56666/7343244)
  - [x] ebt status (if ebt available)
  - [x] add readme
- installers
  - [x] installers working (linux, mac, windows)
  - [x] ask for people to try it with clients

also free code
```js
// example code for ebt polling

var seq = 0
var replication = {}


server.ebt.peerStatus(server.id, (err, data) => {
  if (err) return console.error(err)

  seq = data.seq // this is my actual sequence

  for (var peer in data.peers) {
    replication[peer] = data.peers[peer]
  } // update what the peer says my sequence is at
})
```

**Comment by Powersource** [comment]
Did a basic pass on ebt now so you can get the info out. Gonna make it easier to parse in the future.

**Comment by mixmix** [comment]
Works as intended :heart: 

Great work :pineapple: :tropical_fish:
